import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import fs from "fs";
import path from "path";
import GlobalLayout from "../components/layout/GlobalLayout";
import { EventTemplateData } from "../components/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read data from data.json
  const filePath = path.join(process.cwd(), 'components', 'data', 'data.json');
  const fileContents = fs.readFileSync(filePath, 'utf8');
  const fullData = JSON.parse(fileContents) as EventTemplateData;

  const headerData = fullData.common.Header;
  const footerData = fullData.common.Footer;
  
  // Extract all page banners
  const banners: Record<string, any> = {};
  const pages = fullData.categories.Event.templateComponents['template-2'].pages;
  const sections = fullData.categories.Event.sections;

  Object.entries(pages).forEach(([pageKey, pageData]) => {
    const bannerComp = pageData.components?.find(c => c.key === "PageBanner");
    if (bannerComp && sections.PageBanner) {
      banners[pageKey] = sections.PageBanner.variants[bannerComp.component];
    }
  });

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-x-hidden bg-black text-white`}
      >
        <GlobalLayout headerData={headerData} footerData={footerData} banners={banners}>
          {children}
        </GlobalLayout>
      </body>
    </html>
  );
}
